version: '2'
services:
  db:
    extends:
      file: ../db/docker-compose.yml
      service: db
  user:
    build:
      context: .
      args:
        env: dev
    depends_on:
      - db
    links:
      - db
    ports:
      - 4000:4000
    volumes:
      - ./mix.exs:/app/mix.exs
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./test:/app/test
      - ./web:/app/web
    env_file: .env
    environment:
      - MIX_ENV=dev
      - POSTGRES_DB=user_dev
    command: mix dev
